steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/containers/playing_with_git:latest', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/containers/playing_with_git:latest']
    timeout: 500s
  - name: gcr.io/cloud-builders/gcloud
    args:
    - kms
    - decrypt
    - --ciphertext-file=${_DEPLOY_KEY_ENC}
    - --plaintext-file=${_DEPLOY_KEY}
    - --location=global
    - --keyring=${_KEYRING_NAME}
    - --key=${_KEY_NAME}
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - compute
    - ssh
    - ${_INSTANCE_NAME}
    - --force-key-file-overwrite
    - --zone=${_INSTANCE_ZONE}
    - --ssh-key-file=${_DEPLOY_KEY}
    - --command=docker pull gcr.io/$PROJECT_ID/containers/playing_with_git:latest && (docker stop ${_APP_NAME} || true) && (docker rm ${_APP_NAME} || true) && docker run --name ${_APP_NAME} -d -p ${_IP_ADDRESS_PORT}:3000 gcr.io/$PROJECT_ID/containers/playing_with_git:latest